package Exception;

public class E1 
{
	

	public static void main(String[] args) 
	{
		try
		{
		int a=10;
		int b=0;
        int c=a/b;
		}
		catch(ArithmeticException i)
		{
			System.out.println("hello");
		}
		
	   
		System.out.println("hi");
		
		
	}}
		

	


